name: CI Pipeline

# Permissions minimales déclarées au niveau du workflow
permissions:
  contents: read

on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Install Python 3.12
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
        with:
          python-version: '3.12'

      - name: Checkout project 
        uses: actions/checkout@v4 # official reference for GitHub checkout service

      - name: Install Dependancies
        run: | 
          python -m pip install --upgrade pip
          pip install uv
          uv sync
      
      - name: Lancer les tests
        run: .venv/bin/py.test
    